development:
  sessions:
    default:
      database: people_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: people_test
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
